services:
  ao-analytics-frontend:
    container_name: ao-analytics-frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUBLIC_BACKEND_URL=http://localhost:8080
      - PUBLIC_RENDER_URL=https://render.albiononline.com
    ports:
      - 8000:80
    restart: unless-stopped
