services:
  ao-analytics-frontend:
    container_name: ao-analytics-frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - PUBLIC_BACKEND_URL=http://localhost:8080
    ports:
      - 8000:80
    restart: unless-stopped
